### ISSUE TITLE
seems_utf8 is wrong

### ISSUE THREAD

**Issue by robinsherwood** [jensensen/keycloud-for-phpwcms#1]
Change line 206

if(seems_utf8($allkeywds)) 

into

if(phpwcms_seems_utf8($allkeywds)) 

Have a look too: http://forum.phpwcms.org/viewtopic.php?p=142587#p142587
Tagcloud has phpwcms_seems_utf8 already :)

**Comment by jensensen** [comment]
Thank you!
Has been fixed.

Det funzt - da legst di nieder.
Dank und Gruß, lieber Claus!
